name: ExtDN Unit Tests
on: [push]

env:
  MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
  MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
  MODULE_NAME: ${{ secrets.MODULE_NAME }}
  COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}

jobs:
  unit-tests:
    name: Magento 2 Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: mkdir /tmp/composer-files && composer -g config cache-files-dir /tmp/composer-files

      - uses: actions/cache@v4
        with:
          path: /tmp/composer-files
          key: ${{ runner.os }}-composer
          restore-keys: ${{ runner.os }}-composer

      - uses: extdn/github-actions-m2/magento-unit-tests/8.3@master
        env:
          MAGENTO_VERSION: '2.4.7-p2'
